#ifndef OAVL_IDS_H 
#define OAVL_IDS_H

typedef enum {
OAVL_POSITION_EV = 0,
    OAVL_ENGINESTART_EV = 1,
    OAVL_ENGINECUTOFF_EV = 2,
    OAVL_PANIC_EV = 3,
    OAVL_SUDDENBREAK_EV = 4,
    OAVL_SUDDENACCELERATION_EV = 5,
    OAVL_SHARPTURN_EV = 6,
    OAVL_STOPPEDSTART_EV = 7,
    OAVL_STOPPEDEND_EV = 8,
    OAVL_SPEEDSTART_EV = 9,
    OAVL_SPEEDSTOP_EV = 10,
    OAVL_BATTERY_EV = 11,
    OAVL_INPUT_EV = 12,
    OAVL_HANDSHAKE_EV = 13,
    OAVL_SYNCHRONIZE_EV = 14,
    OAVL_IDENTITY_EV = 15
} OpenAvlIds;

#endif